; *** This file is automatically generated by Plesk ***
$TTL	86400

@	IN	SOA	ns.mcmurtreygallery.com. roni.mcmurtreygallery.com. (
			1417267837	;AUTO_INCREMENT
			10800	; Refresh
			3600	; Retry
			604800	; Expire
			10800 )	; Minimum

mcmurtreygallery.com.				IN NS	 ns.mcmurtreygallery.com.
ns.mcmurtreygallery.com.			IN A	 104.131.56.122
webmail.mcmurtreygallery.com.		IN A	 174.122.149.156
cpanel.mcmurtreygallery.com.		IN A	 174.122.149.156
whm.mcmurtreygallery.com.		 	IN A	 174.122.149.156
webdisk.mcmurtreygallery.com.		IN A	 174.122.149.156
mail.mcmurtreygallery.com.		 	IN A	 192.254.250.18
mcmurtreygallery.com.		 		IN A	 104.236.51.134
ftp.mcmurtreygallery.com.		 	IN CNAME	mcmurtreygallery.com.
www.mcmurtreygallery.com.		 	IN CNAME	mcmurtreygallery.com.
mcmurtreygallery.com.		 		IN MX 10 	gator3293.hostgator.com.
mcmurtreygallery.com.		 		IN TXT	 	"v=spf1 +a +mx -all"
