; *** This file is automatically generated by Plesk ***
$TTL	86400

@	IN	SOA	ns.quickshipcellular.com. asad.dadesigners.com. (
			1368999099	; Serial
			10800	; Refresh
			3600	; Retry
			604800	; Expire
			10800 )	; Minimum

quickshipcellular.com.		 		IN NS	 ns.quickshipcellular.com.
ns.quickshipcellular.com.			IN A	 104.131.56.122
quickshipcellular.com.		 		IN A	 104.236.51.134
www.quickshipcellular.com.		 	IN CNAME quickshipcellular.com.
