; *** This file is automatically generated by Plesk ***
$TTL	86400

@	IN	SOA	ns.woodbridge-agent.com. asad.dadesigners.com. (
			1497167805	;AUTO_INCREMENT
			10800	; Refresh
			3600	; Retry
			604800	; Expire
			10800 )	; Minimum

woodbridge-agent.com.		 IN NS	 ns.woodbridge-agent.com.
ns.woodbridge-agent.com.		 IN A	 108.210.135.156
woodbridge-agent.com.		 	 IN A	 74.208.231.34
webmail.woodbridge-agent.com.		 IN A	 74.208.231.34
mail.woodbridge-agent.com.		 IN A	 74.208.231.34
ftp.woodbridge-agent.com.		 IN CNAME	 woodbridge-agent.com.
www.woodbridge-agent.com.		 IN CNAME	 woodbridge-agent.com.
woodbridge-agent.com.		 IN MX	10 mail.woodbridge-agent.com.
woodbridge-agent.com.		 IN TXT	 "v=spf1 +a +mx -all"
