; *** This file is automatically generated by Plesk ***
$ORIGIN quickshipcellular.com.
$TTL	86400

@	IN	SOA	ns.quickshipcellular.com. asad.dadesigners.com. (
			1369999099	; Serial
			10800	; Refresh
			3600	; Retry
			604800	; Expire
			10800 )	; Minimum

@	 		IN NS	 ns.quickshipcellular.com.
ns			IN A	 104.131.56.122
@                       IN NS    ns1.dadesigners.com.
@                       IN NS    ns2.dadesigners.com.
@	 		IN A	 104.236.51.134
www		 	IN CNAME quickshipcellular.com.
